[package]
name = "lib3h"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[dependencies]
byteorder = "1.2"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.3.2"
Inflector = "0.11.3"
lazy_static = "1.0"
num-bigint = "0.2.0"
num-traits = "0.2.5"
openssl = "0.10.10"
rand = "0.5.1"
regex = "1.0"
ring = "0.12.1"
rust-base58 = "0.0.4"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.13.7"
serde_json = { version = "1.0", features = ["preserve_order"] }
tiny-keccak = "1.4"
