[package]
name = "lib3h_half_busy_chat"
version = "0.0.7"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "lib3h simulation test framework"
keywords = ["holochain", "holo"]
categories = ["development-tools::testing"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/lib3h_half_busy_chat"
repository = "https://github.com/holochain/lib3h"

[dependencies]
crossbeam-channel = "=0.3.8"
linefeed = "=0.6.0"

[lib]
name = "lib3h_half_busy_chat"
path = "src/lib.rs"

[[bin]]
name = "half_busy_chat"
path = "src/main.rs"
